/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package letterguessgame;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author dell
 */
public class GameForm extends javax.swing.JFrame {
    private UIManager.LookAndFeelInfo[] looks; // look and feels

    /**
     * Creates new form GameForm
     */
    public GameForm() {
        initComponents();
        setTitle("Letter Guessing Game");
        looks = UIManager.getInstalledLookAndFeels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        newGameBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        metalTheme = new javax.swing.JRadioButtonMenuItem();
        nimbusTheme = new javax.swing.JRadioButtonMenuItem();
        motifTheme = new javax.swing.JRadioButtonMenuItem();
        windowsTheme = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 700));
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newGameBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newGameBtn.setText("New Game");
        newGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBtnActionPerformed(evt);
            }
        });
        jPanel2.add(newGameBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 170, 93));

        quitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quitBtn.setText("QUIT");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(quitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 175, 101));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letterguessgame/background.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 900, 690));

        jMenu1.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(newMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");

        jMenu3.setText("Themes");

        buttonGroup1.add(metalTheme);
        metalTheme.setText("Metal");
        metalTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metalThemeActionPerformed(evt);
            }
        });
        jMenu3.add(metalTheme);

        buttonGroup1.add(nimbusTheme);
        nimbusTheme.setText("Nimbus");
        nimbusTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimbusThemeActionPerformed(evt);
            }
        });
        jMenu3.add(nimbusTheme);

        buttonGroup1.add(motifTheme);
        motifTheme.setText("CDE/Motif");
        motifTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motifThemeActionPerformed(evt);
            }
        });
        jMenu3.add(motifTheme);

        buttonGroup1.add(windowsTheme);
        windowsTheme.setText("Windows");
        windowsTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowsThemeActionPerformed(evt);
            }
        });
        jMenu3.add(windowsTheme);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(aboutMenuItem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_quitBtnActionPerformed

    private void newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameBtnActionPerformed
        dispose();
        NewGameForm newGameForm = new NewGameForm();
        newGameForm.setVisible(true);
    }//GEN-LAST:event_newGameBtnActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        dispose();
        GameForm form = new GameForm();
        form.setVisible(true);
    }//GEN-LAST:event_newMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void metalThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metalThemeActionPerformed
        changeTheLookAndFeel(0);
    }//GEN-LAST:event_metalThemeActionPerformed

    private void nimbusThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimbusThemeActionPerformed
        changeTheLookAndFeel(1);
    }//GEN-LAST:event_nimbusThemeActionPerformed

    private void motifThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motifThemeActionPerformed
        changeTheLookAndFeel(2);
    }//GEN-LAST:event_motifThemeActionPerformed

    private void windowsThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsThemeActionPerformed
        changeTheLookAndFeel(3);
    }//GEN-LAST:event_windowsThemeActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        JOptionPane.showMessageDialog(null, "This game is designed and programmed by\n"
                + "two master of Computer Engineering students of\n Cyprus International University\n\n"
                + "Name: Aizaz Ali Shah\n"
                + "Email: Aizaz319@gmail.com\n"
                + "Name: Jana Al Hajj\n"
                + "Email: janahajj187@gmail.com\n"
                + "Cprus International University\n",
                "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem metalTheme;
    private javax.swing.JRadioButtonMenuItem motifTheme;
    private javax.swing.JButton newGameBtn;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JRadioButtonMenuItem nimbusTheme;
    private javax.swing.JButton quitBtn;
    private javax.swing.JRadioButtonMenuItem windowsTheme;
    // End of variables declaration//GEN-END:variables

    private void changeTheLookAndFeel(int value) {
        try // change look-and-feel
        {

            // set look-and-feel for this application
            UIManager.setLookAndFeel(looks[value].getClassName());
            // update components in this application
            SwingUtilities.updateComponentTreeUI(this);

        } // end try
        catch (Exception exception) {
            exception.printStackTrace();
        } // end catch
    } // end method changeTheLookAndFeel
    
    }
